// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizBowlDiscordScoreTracker.Database;

namespace QuizBowlDiscordScoreTracker.Migrations
{
    [DbContext(typeof(BotConfigurationContext))]
    [Migration("20201023173542_ExportThrottle")]
    partial class ExportThrottle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("QuizBowlDiscordScoreTracker.Database.GuildSetting", b =>
                {
                    b.Property<ulong>("GuildSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExportCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastExportDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamRolePrefix")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseBonuses")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildSettingId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("QuizBowlDiscordScoreTracker.Database.TextChannelSetting", b =>
                {
                    b.Property<ulong>("TextChannelSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildSettingId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("TeamMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("VoiceChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TextChannelSettingId");

                    b.HasIndex("GuildSettingId");

                    b.ToTable("TextChannels");
                });

            modelBuilder.Entity("QuizBowlDiscordScoreTracker.Database.UserSetting", b =>
                {
                    b.Property<ulong>("UserSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CommandBanned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExportCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastExportDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserSettingId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuizBowlDiscordScoreTracker.Database.TextChannelSetting", b =>
                {
                    b.HasOne("QuizBowlDiscordScoreTracker.Database.GuildSetting", null)
                        .WithMany("TextChannels")
                        .HasForeignKey("GuildSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
